#
# DigitalOcean App Platform Configuration
# Scorpion Security Hub - Full Stack Deployment
#

name: scorpion-security-hub
region: nyc

# Static Site (Frontend)
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: your-username/scorpion-security-hub
    branch: main
  build_command: echo "No build step required for static frontend"
  output_dir: /
  index_document: index.html
  error_document: pages/404.html
  routes:
  - path: /pages
  - path: /js
  - path: /css
  - path: /public
  environment_slug: node-js
  
# Backend API Service
services:
- name: api
  source_dir: /server
  github:
    repo: your-username/scorpion-security-hub
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  
  # Environment Variables
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: SUPABASE_URL
    value: ${SUPABASE_URL}
  - key: SUPABASE_ANON_KEY
    value: ${SUPABASE_ANON_KEY}
  - key: SUPABASE_SERVICE_ROLE_KEY
    value: ${SUPABASE_SERVICE_ROLE_KEY}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: BCRYPT_ROUNDS
    value: "12"
  - key: CORS_ORIGIN
    value: "https://scorpion-security-hub-frontend.ondigitalocean.app,https://www.yourdomain.com"

# Health Checks
health_checks:
- name: api-health
  http_path: /api/health
  initial_delay_seconds: 30
  period_seconds: 10
  timeout_seconds: 5
  success_threshold: 1
  failure_threshold: 3

# Alerts
alerts:
- rule: CPU_UTILIZATION
  disabled: false
- rule: MEM_UTILIZATION  
  disabled: false
- rule: RESTART_COUNT
  disabled: false

# Domains (configure after deployment)
domains:
- domain: yourdomain.com
  type: PRIMARY
- domain: www.yourdomain.com
  type: ALIAS